### PR TITLE
using submodules for cookbooks

### PR DESCRIPTION
**Pull request by mhenke**
I saw this technique in another git repository. pretty cool.

### CODE REVIEW

**Comment by modius** [comment]
I would recommend using Librarian-Chef as the way to manage the versioning of recipes in the Cookbook itself:
https://github.com/applicationsonline/librarian-chef

**Comment by mhenke** [comment]
That is an option but requires the user to install the librarian gem. It's
there an issue you see with git submodules?

**Comment by modius** [comment]
A single Cheffile in the repo just seems a lot more elegant. Plus if the user has managed to get this far, a gem install is probably not too arduous ;)

**Comment by modius** [comment]
That said... looks like librarian-chef has been set to require --pre so I may have been a little bit too optimistic! Further down the track perhaps.

**Comment by mhenke** [comment]
I'd say go ahead and switch it over then do a pull request but still unsure
of the benefit. I'll have to checkout librarian more.

**Comment by devalnor** [comment]
Librarian-chef seems to be a very young project (0.0.1.beta.1.) but I'm curious about it.

**Pull request merged**
